### ISSUE TITLE
Add transformation from 2MASS system to each telescope natural system

### ISSUE THREAD

**Issue by rhandberg** [SNflows/flows#39] opened 2022-02-08 10:13 UTC
### [Issue moved from old repo. Originally posted by @lgalbany ]

As discussed on Nov 4th in Barcelona, it would be good to have already included in the pipeline the transformation between the catalogued 2MASS stars catalogs to the system of each of the telescopes, so then the SN gets calibrated directly in the natural system of the telescope.

This basically means that color terms are included and J/H magnitudes form 2MASS are transformed to CAHA/NOT/NTT/CMO/... before being used to calibrate the SN.

**Comment by emirkmo** [comment] 2022-06-26 07:54
Duplicate of #24

**Closed as not planned by emirkmo** 2022-06-26 07:54 UTC
Labels: duplicate
